name: Release

on:
  workflow_dispatch: {}

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Get version
        id: version
        run: echo "::set-output name=version::$(cargo read-manifest | jq .version -r)"
      - uses: actions/github-script@v8
        name: Create draft release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require("fs").promises;

            const currentVersionChangesRegex = /## ${{ steps.version.outputs.version }}$(.*?)$\n##[^#]/ms;

            const changelog = await fs.readFile("CHANGELOG.md", "utf8");
            const changes = changelog.match(currentVersionChangesRegex)[1].trim();

            console.log("Creating draft release for ${{ steps.version.outputs.version }}");

            await github.repos.createRelease({
                ...context.repo,
                draft: true,
                name: "dht-sensor v${{ steps.version.outputs.version }}",
                target_commitish: "${{ github.sha }}",
                tag_name: "v${{ steps.version.outputs.version }}",
                body: changes,
            });
